#version 300 es
precision highp float;

in vec2 vUv;
uniform sampler2D tMap;
uniform vec3 uColor;

out vec4 FragData[1];

void main() {
    vec3 tex = texture(tMap, vUv).rgb;
    float signedDist = max(min(tex.r, tex.g), min(max(tex.r, tex.g), tex.b)) - 0.5;
    float d = fwidth(signedDist);
    float alpha = smoothstep(-d, d, signedDist);

    if(alpha < 0.01)
        discard;

    FragData[0].rgb = uColor;
    FragData[0].a = alpha;
}
